.\" This source code is released into the public domain.
.Dd June 3, 2025
.Dt ACME.CONF 5
.Os
.Sh NAME
.Nm acme.conf
.Nd lfacme global configuration file
.Sh SYNOPSIS
.Pa /usr/local/etc/lfacme/acme.conf
.Sh DESCRIPTION
The
.Nm
file is used to configure the global behaviour of
.Nm lfacme .
Each option should be configured as a
.Xr sh 1
variable assignment, i.e.
.Dq Ar option Ns = Ns Ar value .
.Pp
Alternatively, options may be set as environment variables prior to running
.Nm lfacme
utilities.
If all required options are set in the environment, then creating the
.Nm
file is not required.
.Pp
The following configuration variables are supported:
.Bl -tag -width indent
.It Va ACME_URL
(Required.)
The URL of the ACME server.
.It Va ACME_DATADIR
The path to the runtime data directory, where the ACME account key and any
issued certificates will be stored.
The default value is
.Pa /var/db/lfacme .
.It Va ACME_HOOKDIR
The path to a directory containing hooks to invoke when issuing certificates
(see
.Xr domains.conf 5 ) .
The default value is
.Pa /usr/local/etc/lfacme/hooks .
.El
.Pp
Additional configuration variables may be used by the ACME validation hooks;
refer to the manual page for each hook for more details.
.Sh SEE ALSO
.Xr domains.conf 5 ,
.Xr lfacme-renew 8 ,
.Xr lfacme-setup 8
