.\" This source code is released into the public domain.
.Dd June 3, 2025
.Dt LFACME-SETUP 8
.Os
.Sh NAME
.Nm lfacme-setup
.Nd create a new ACME account
.Sh SYNOPSIS
.Nm
.Op Fl vy
.Op Fl c Ar confdir
.Sh DESCRIPTION
The
.Nm
utility will register a new account with the ACME provider configured in
.Xr acme.conf 5 .
If the provider requires accepting terms of service to create an account,
the ToS URL will be printed and
.Nm
will prompt the user to accept them.
.Pp
The follow options are accepted:
.Bl -tag -width indent
.It Fl c Ar confdir
Use
.Ar confdir
as the configuration directory instead of the default
.Pa /usr/local/etc/lfacme .
.It Fl v
Produce more output when running.
This also passes the
.Fl v
option to uacme.
.It Fl y
If the ACME provider requires accepting terms of service,
accept the provided terms automatically.
.El
.Sh ENVIRONMENT
Refer to
.Xr lfacme 8
for a list of environment variables which affect the operation of
.Nm .
.Sh SEE ALSO
.Xr acme.conf 5 ,
.Xr lfacme 7
